<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<html>

<!-- Mirrored from cppreference.com/keywords/throw.html by HTTrack Website Copier/3.x [XR&CO'2004], Tue, 22 Jan 2008 06:23:12 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=iso-8859-1"><!-- /Added by HTTrack -->
<head>
  <meta name="generator" content=
  "HTML Tidy for Linux/x86 (vers 1 September 2005), see www.w3.org">

  <title>throw</title>
  <link href="../cppreference.css" rel="stylesheet" type="text/css">
  <link href="../prettify.css" type="text/css" rel="stylesheet" />
  <script type="text/javascript" src="../prettify.js"></script>
</head>

<body onload="prettyPrint()">
<table>
  <tr>
  <td>
  <div class="body-content">

  <div class="header-box">
    <a href="../index-2.html">cppreference.com</a> &gt; <a href=
    "index.html">C/C++ Keywords</a> &gt; <a href="throw.html">throw</a>
  </div>

  <div class="name-format">
    throw
  </div>

  <div class="syntax-name-format">
    Syntax:
  </div>
  <pre class="syntax-box">
  try {
  statement list;
  }
  catch( typeA arg ) {
  statement list;
  }
  catch( typeB arg ) {
  statement list;
  }
  ...
  catch( typeN arg ) {
  statement list;
  }
</pre>

  <p>The throw statement is part of the C++ mechanism for exception
  handling. This statement, together with the <a href=
  "try.html">try</a> and <a href="catch.html">catch</a> statements, the
  C++ exception handling system gives programmers an elegant mechanism
  for error recovery.</p>

  <p>You will generally use a <a href="try.html">try</a> block to
  execute potentially error-prone code. Somewhere in this code, a throw
  statement can be executed, which will cause execution to jump out of
  the <a href="try.html">try</a> block and into one of the <a href=
  "catch.html">catch</a> blocks. For example:</p>
<pre class="prettyprint">
   try {
     cout &lt;&lt; &quot;Before throwing exception&quot; &lt;&lt; endl;
     throw 42;
     cout &lt;&lt; &quot;Shouldn&#39;t ever see this&quot; &lt;&lt; endl;
   }
   catch( int error ) {
     cout &lt;&lt; &quot;Error: caught exception &quot; &lt;&lt; error &lt;&lt; endl;
   }            
</pre>

  <div class="related-name-format">
    Related topics:
  </div>

  <div class="related-content">
    <a href="catch.html">catch</a><br>
    <a href="try.html">try</a>
  </div>
  </div>
  </td>
  

<script src="../../www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-2828341-1";
urchinTracker();
</script>
  </tr>
  </table>
</body>
<!-- Mirrored from cppreference.com/keywords/throw.html by HTTrack Website Copier/3.x [XR&CO'2004], Tue, 22 Jan 2008 06:23:12 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=iso-8859-1"><!-- /Added by HTTrack -->
</html>
